name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.6'

    - name: Configure Kaggle API
      run: |
        mkdir -p ~/.kaggle
        echo "{\"username\":\"${{secrets.KAGGLE_USERNAME}}\",\"key\":\"${{secrets.KAGGLE_KEY}}\"}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r ./project/requirements.txt

    - name: Run tests
      run: |
        python ./project/tests.py
